name: Site
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'site/**'
  release:
    types:
      - published
jobs:
  publish-website:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Compile
        run: sbt compile
      - name: Generate site
        run: make build-site
      - name: Publish
        uses: cloudflare/wrangler-action@3.13.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish --project-name=zio-temporal build/
          workingDirectory: 'website'